### ISSUE TITLE
Hub Scan task fails while generating risk report

### ISSUE THREAD

**Issue by rutherfordjw** [blackducksoftware/hub-bamboo#17] opened 2016-09-13 19:00 UTC
After scanning docker image (as a tarball) with bamboo task. It fails FileNotFoundException to generate the report due to a null pointer

``` bash
simple  13-Sep-2016 14:33:51    Logging to file: /opt/app/code/automate/agent/xml-data/build-dir/CODE-META47-SCAN/HubScanLogs/17/log/c3cuautomate10.premierinc.com-meta-app.tar-2016-09-13T182942.127Z.log
simple  13-Sep-2016 14:33:51    Hub CLI return code : 0
simple  13-Sep-2016 14:33:51    You can view the BlackDuck Scan CLI logs at : '/opt/app/code/automate/agent/xml-data/build-dir/CODE-META47-SCAN/HubScanLogs/17'
simple  13-Sep-2016 14:33:51    
simple  13-Sep-2016 14:33:51    Generating Risk Report
simple  13-Sep-2016 14:33:51    Checking the directory : /opt/app/code/automate/agent/xml-data/build-dir/CODE-META47-SCAN/HubScanLogs/17/status for the scan status's.
error   13-Sep-2016 14:36:22    Error occurred while running Task '(6)' of type com.blackducksoftware.integration.hub-bamboo:hubScanTask.
error   13-Sep-2016 14:36:22    java.lang.NullPointerException
error   13-Sep-2016 14:36:22        at com.blackducksoftware.integration.hub.report.api.HubRiskReportData.setReport(HubRiskReportData.java:79)
error   13-Sep-2016 14:36:22        at com.blackducksoftware.integration.hub.report.api.RiskReportGenerator.generateHubReport(RiskReportGenerator.java:82)
error   13-Sep-2016 14:36:22        at com.blackducksoftware.integration.hub.bamboo.tasks.HubScanTask.generateRiskReport(HubScanTask.java:726)
error   13-Sep-2016 14:36:22        at com.blackducksoftware.integration.hub.bamboo.tasks.HubScanTask.execute(HubScanTask.java:227)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$124(TaskExecutorImpl.java:269)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:202)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:269)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:108)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:74)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:215)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:139)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:130)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:215)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:129)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:137)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
error   13-Sep-2016 14:36:22        at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
error   13-Sep-2016 14:36:22        at java.lang.Thread.run(Thread.java:745)
```

contents of directory "17"

``` bash
[root@c3cuautomate10 HubScanLogs]# ls 17/
CLI_Output.txt  log
```

**Comment by akamen** [comment] 2016-10-04 19:46
@rutherfordjw Are you able to scan that same file using the CLI as a standalone process?   Trying to determine if this is a Bamboo problem or a CLI problem.

**Comment by jrichardBD** [comment] 2016-12-02 16:53
Cannot reproduce with the latest. Should be fixed

**Closed by jrichardBD** 2016-12-02 16:53 UTC
Labels: bug
